### ISSUE TITLE
Species form of query tree is not deactivated on validate

### ISSUE THREAD

**Issue by misdoro** [VAMDC/VAMDC-Portal#8]
Rigt now one can click twice on validate of species form of query tree, and get two times the number of species chosen.
Maybe add links to enable adding new forms?
It will reduce number of clicks required.
Like 
Number of atoms <add>   XXv
Number of molecules <add> YYv
Number of particles <add> ZZv
validate

**Comment by nicolasmoreau** [comment]
Lock the button once the species have been chosen.
A new button can unlock the form
